### ISSUE TITLE
State of the art result?

### ISSUE THREAD

**Issue by eric-haibin-lin** [ylongqi/openrec#24]
Is there any example of using openrec to reproduce models in SOTA papers? Thanks!

**Comment by ylongqi** [comment]
Yes, we are working on those examples. They will be released by the end of August. We will be also presenting more examples in the following two events:

Strata data conference:
https://conferences.oreilly.com/strata/strata-ny/public/schedule/detail/68280

Recsys 2018:
https://recsys.acm.org/recsys18/tutorials/#content-tab-1-1-tab

**Comment by eric-haibin-lin** [comment]
Thanks! That's an awesome effort. Would you mind mentioning what examples are you targeting(e.g. FM? MF? Wide&Deep?)? I found very little reference implementation for recsys publications, and am curious what you'll be covering here

**Comment by ylongqi** [comment]
We will be mainly adding Neural Network based methods. That being said, Wide&Deep, Collaborative Metric Learning, RNN-based approaches, MLP-based approaches (e.g., Neural Collaborative Filtering, AutoEncoder, etc.). Traditional MF-based methods have been largely covered in the framework already (e.g., BPR, PMF, etc.). We are also open to paper suggestions to maximize OpenRec's utility to the community, so please post interesting papers in this thread - We will consider them seriously :)
