### ISSUE TITLE
How to get user and item embedddings from a trained model ?

### ISSUE THREAD

**Issue by mohammad1234** [ylongqi/openrec#34]
I've followed the tutorial and was able to train a model successfully. But how to get user and item embeddings from a trained model ?

**Comment by ylongqi** [comment]
You can use the the `train_inspect_ports` function or `serve_inspect_ports`. These function basically runs a forward pass and retrieve the values of specified ports. For example, to get item embedding and item bias, you can do:

`item_embedding, item_bias = model.train_inspect_ports(batch_data={'item_id': range(total_items)}, ports=[model.traingraph.itemgraph['item_vec'], model.traingraph.itemgraph['item_bias']])
`

To get user embedding, you can do:

`user_embedding = model.train_inspect_ports(batch_data={'user_id': range(total_users)}, ports=[model.traingraph.itemgraph['user_vec']])
`

**Comment by mohammad1234** [comment]
@ylongqi thanks for you reply, i tried your approach but i need some further help with the function :
`model.traingraph.itemgraph['item_vec']` or `model.traingraph.usergraph['user_vec']` always returns a matrix of size `[batch_size, dim]`.

So if number of users or number of items are greater than the batch size then it returns an error. How to create such a `batch_data` which matches with `batch_size` and pass to `model.train_inspect_ports` ? Thanks in advance.

**Comment by ylongqi** [comment]
@mohammad1234 The reason why train graph returns a fixed batch size because the input to train graphs are fixed. If you want varied batch size, you can use serve graph. In other words:

`user_embedding = model.serve_inspect_ports(batch_data={'user_id': range(total_users)}, ports=[model.servegraph.itemgraph['user_vec']])`

**Comment by ylongqi** [comment]
Essentially, replace the `train_inspect_ports` function with `serve_inspect_ports`, and replace `traingraph` with `itemgraph`.

**Comment by mohammad1234** [comment]
Great. Thanks
