### ISSUE TITLE
How to load model and test with serve?

### ISSUE THREAD

**Issue by baophamtd** [ylongqi/openrec#39]
Hi there. I also another opened ticket, but that's almost settled. To avoid confusions, I'm making a new ticket here regarding how to test the model:
After training, I have couple files and they're named like this `model.ckpt-40000.data-00000-of-00001`.
@ylongqi showed me how to test using the `serve` method. However, the only argument I can feed in data for that method is `batch_data`. Right now, each of the entries in my numpy array looks like this `(143 135 5)` denoting `user_id`, `item_id` and `rating`
Would someone mind to provide and example on how to load the model and call serve method to test as I couldn't find any example for it? Thank you very much!

**Comment by ylongqi** [comment]
After you train the model, you can use `model.restore(save_model_dir='XXXX', restore_serve=True)` to load the model. Then to evaluate, just prepare batch_data as the following code shows: 

https://github.com/ylongqi/openrec/blob/master/openrec/utils/samplers/random_pointwise_sampler.py#L11

Essentially, batch_data is a structured numpy array with three keys, "user_id", "item_id", and "label". In your case, user_id=143, item_id=135, and label=5.

Hope this example helps!

**Comment by baophamtd** [comment]
@ylongqi Thank you for your response. I have tried to restore the model, but not sure if I'm doing it correctly cause it's giving me this error: 
```
self._optimistic_restore(self._tf_serve_sess, os.path.join(save_model_dir, 'model.ckpt'))
AttributeError: 'Recommender' object has no attribute '_tf_serve_sess'
```
Here is my codes. Can you let me know if there's any issues?
```
from openrec.recommenders import Recommender
import numpy as np

recommender = Recommender(train=True, serve=True)
model = recommender.restore(save_model_dir='./bpr_recommender/model.ckpt-40000.data-00000-of-00001', restore_serve=False)

input_npy = np.zeros(1, dtype=[('user_id', np.int32), ('item_id', np.int32), ('rating', np.float32)])
input_npy[0] = (4, 5, 3)
model.serve(input_npy)
```

**Comment by ylongqi** [comment]
You need to build the recommender before loading it, i.e., in your code you should call:

recommender.build()

before calling recommender.restore(...)

If you use the ModelTrainer, this has already been handled by the trainer:

https://github.com/ylongqi/openrec/blob/master/openrec/model_trainer.py#L14

**Comment by baophamtd** [comment]
@ylongqi Thank you. Would you mind to provide an example of how to use ModelTrainer or point out where it is in the repo if it's already been provided? I have tried to look for an example but couldn't find it.

**Comment by ylongqi** [comment]
The model trainer is here:
https://github.com/ylongqi/openrec/blob/master/openrec/model_trainer.py

Some examples of how to use it (Search for "ModelTrainer")
https://github.com/ylongqi/openrec/blob/master/tutorials/Vanilla_Youtube_Recommender_example.ipynb

Essentially, all the examples provided under the "examples" folder used ModelTrainer:
https://github.com/ylongqi/openrec/tree/master/examples
