### ISSUE TITLE
Feature to export the built servegraph into saved_model.pb

### ISSUE THREAD

**Issue by chlee0925** [ylongqi/openrec#42]
Hi ylongqi. Thanks for the project. I enjoyed playing with the framework.

I have noticed that Recommender object does not have a functionality to export to a [saved_model.pb](https://www.tensorflow.org/api_docs/python/tf/saved_model). This is a very important function for me as I want to serve my model via [tensorflow serving](https://www.tensorflow.org/tfx/guide/serving).

I managed to add the feature myself and would like to contribute to your project. Do you have any CONTRIBUTING.md such that I can follow guidelines if any.

**Comment by buihoang95** [comment]
Same issue here for TF2.0. It's hard to save custom Model objects. Is there any plan for this?

**Comment by ylongqi** [comment]
The issue is addressed for TF2.0. All the models under openrec.tf2.recommenders are instances of tf.keras.Model and can be saved via `save_weights` and loaded via `load_weights`

**Comment by chlee0925** [comment]
Sure closing the issue.

**Comment by chlee0925** [comment]
Thank you for reply
