### ISSUE TITLE
How to get user/item embeddings ?

### ISSUE THREAD

**Issue by justram** [ylongqi/openrec#7]
I've some problems to get the user/item embeddings(or representations) from this framework.
I'm very interested in your CML model. And I want to use it with movielens dataset, and evaluate with other recommendation algorithms like libMF. Is there an option or any plan to implement this feature?

**Comment by ylongqi** [comment]
Thanks for the suggestion! We will implement this feature within the next week.

**Comment by ylongqi** [comment]
This feature has been implemented and included in the master branch. 

Use the function [compute_module_outputs](http://openrec.readthedocs.io/en/latest/recommenders/openrec.recommenders.recommender.html#openrec.recommenders.Recommender.compute_module_outputs) in the recommender to get user/item embeddings, e.g.,

`model.compute_module_outputs('user_vec', batch_data, train=True)`
